### ISSUE TITLE
epic: Espandere le sezioni del sito.

### ISSUE THREAD

**Issue by Byloth** [vuejs-varese/vuejs-varese.github.io#1]
Espandere il sito introducendo nuove pagine, utili alla community e alla sua promozione.

- [ ] **Aggiungere la pagina "Manifesto":**
Dovrà visualizzare il manifesto della community.  
- [ ] **Aggiungere la sezione "Blog":**  
Dovrà visualizzare degli articoli tecnici, a disposizione di chiunque.
- [ ] **Aggiungere la sezione "Eventi":**  
Dovrà visualizzare la lista sia dei prossimi eventi che di quelli passati.  
Inoltra, dovrà dar modo ad un visitatore di sottoporre la propria disponibilità ad ospirate un evento.
- [ ] **Aggiungere la pagina degli "Speaker":**  
Dovrà visualizzare la lista degli speaker che hanno preso parte agli eventi della community.
Inoltra, dovrà dar modo ad un visitatore di sottoporre la candidatura di un proprio talk.
- [ ] **Aggiungere la pagina dei "Talks":**  
Dovrà visualizzare la lista dei talk che sono stati presentati durante i vari eventi.
Inoltra, dovrà dar modo ad un visitatore di sottoporre la candidatura di un proprio talk.
- [ ] **Aggiungere la pagina delle "Aziende":**  
Dovrà visualizzare la lista delle aziende che -nel corso del tempo- hanno collaborato con la community e/o ospitato suoi eventi.
- [ ] **Aggiungere una pagina relativa ai "Progetti":**  
Dovrà visualizzare i progetti in sviluppo e realizzati direttamente o in collaborazione con la community.
- [ ] **Aggiungere una pagina relativa alle "Statistiche":**  
Dovrà visualizzare le stastistiche relative alla community (es. il numero di eventi tenuti, il numero di partecipanti, il numero di birre bevute, ecc...).
- [ ] **Aggiungere la pagina dei "Contatti":**  
Dovrà visualizzare tutte le pagine social e i canali della community.
Inoltre, dovrà dar modo -tramite un form- di contattare la community inviandole un'email.
